Repository upbound/vscode-up, pull requests merged in 2022-02, with the labels that each got.

#15 Move the version back to v.0.0.1
  package.json
Labels: size/XS

#16 fix(docs): for marketplace link
  README.md
  package.json
Labels: size/XS

#18 Add note for minimum version of `up` to use
  README.md
  package.json
Labels: size/XS

#19 Update vsce to resolve CVE in transitive dependency
  package.json
  yarn.lock
Labels: size/L

#20 Update references to `crossplane` to `upbound` and vscode-up
  CONTRIBUTING.md
  README.md
  package.json
Labels: size/S
